services:
  index:
    build:
      context: .
      dockerfile: Dockerfile.index
    volumes:
      - /app/node_modules
    ports:
      - 5000:5000

  socket:
    build:
      context: .
      dockerfile: Dockerfile.socket
    volumes:
      - /app/node_modules
    ports:
      - 8080:8080
