version: '3.1'

services:

  index:
    image: haleck/rip-express-index
    restart: always
    ports:
      - 5000:5000

  socket:
    image: haleck/rip-express-socket
    restart: always
    ports:
      - 8080:8080
